package com.oviro.enums;

public enum NotificationType {

    // Ride lifecycle
    RIDE_REQUEST,
    RIDE_ACCEPTED,
    RIDE_STARTED,
    RIDE_COMPLETED,
    RIDE_CANCELLED,
    RIDE_SCHEDULED,
    DRIVER_ARRIVING,
    DRIVER_ARRIVED,
    DRIVER_LOCATION_UPDATE,

    // Delivery lifecycle
    DELIVERY_REQUESTED,
    DELIVERY_ASSIGNED,
    DELIVERY_PICKED_UP,
    DELIVERY_IN_TRANSIT,
    DELIVERY_COMPLETED,
    DELIVERY_FAILED,

    // Food orders
    FOOD_ORDER_CONFIRMED,
    FOOD_ORDER_READY,
    FOOD_ORDER_PICKED_UP,
    FOOD_ORDER_DELIVERED,
    FOOD_ORDER_CANCELLED,

    // Payment & Wallet
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    WALLET_RECHARGED,
    WALLET_TRANSFER,
    TIP_RECEIVED,
    REFUND_PROCESSED,
    PROMO_ACTIVATED,

    // SOS
    SOS_ALERT,
    CLIENT_SOS_ALERT,

    // Promotions & Marketing
    PROMO_OFFER,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_ACTIVATED,

    // Referral
    REFERRAL_BONUS_EARNED,
    REFERRAL_INVITE_ACCEPTED,

    // Support
    SUPPORT_TICKET_OPENED,
    SUPPORT_TICKET_REPLIED,
    SUPPORT_TICKET_RESOLVED,

    // Social
    RATING_REQUEST,
    NEW_MESSAGE,
    CHAT_MESSAGE,

    // Driver management
    DRIVER_APPROVED,
    DRIVER_SUSPENDED,
    DRIVER_KYC_REQUIRED,
    DRIVER_BONUS_EARNED
}
