package com.oviro.enums;

public enum TransactionType {
    RECHARGE,
    RIDE_PAYMENT,
    DELIVERY_PAYMENT,
    FOOD_ORDER_PAYMENT,
    COMMISSION,
    WITHDRAWAL,
    WITHDRAWAL_REQUEST,
    REFUND,
    BONUS,
    REFERRAL_BONUS,
    PROMO_CREDIT,
    TIP,
    TRANSFER_DEBIT,
    TRANSFER_CREDIT,
    SUBSCRIPTION_PAYMENT
}
